version: '3.8'
services:
  react-app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start
    ports:
      - "3000:3000"
    labels:
      - "traefik.http.routers.react-app.rule=Host(`localhost`)"
      - "traefik.http.services.react-app.loadbalancer.server.port=3000"
    environment:
      - CHOKIDAR_USEPOLLING=true